@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam actorStyle awesome
actor "Клиент" as cl


participant "Клиентское \nприложение \nпо заказу такси" as cl_app

box "Контур ИС" #lightyellow
participant "ИС распределения заявок \nслужбы такси" as orch
database "DB" as db
end box

participant "Приложение \nдля водителей" as dr_app
actor "Водители" as dr


cl->cl_app: **Регистрируется в приложении:** \n*Номер телефона клиента \n*Имя клиента
group Выбор параметров
cl->cl_app: \n*Желаемая категория машины\n*Желаемое время подачи \n*Заказ такси другому пользователю \n*Тип оплаты

end
dr->dr_app: **Передает данные:**\n*Категория машины \n*Статус машины\n*Номер машины\n*Имя водителя\n*Номер телефона водителя\n*Адрес расположения машины
cl->cl_app: **Формирует заказ:**\n*Адрес подачи машины\n*Адрес назначения
cl_app -> orch: **Передает данные:**\n*Адрес подачи машины \n*Номер телефона клиента \n*Имя клиента \n*Желаемая категория машины\n*Тип оплаты
activate orch #green
dr_app->orch: **Передает данные:** \n*Категория машины \n*Статус машины\n*Номер машины\n*Имя водителя\n*Номер телефона водителя\n*Адрес расположения машины

activate orch #lightgreen
group Выбор параметров
orch->cl_app: Предлагает прежние \nадреса назначения
orch->db: Запрашивает данные \nо предыдущих поездках
db-->orch : Предлагает прежние \nадреса назначения
end
orch->orch : Определение свободной машины
orch->orch : Расчет времени подачи
orch->orch : Расчет стоимости
deactivate orch
orch-->cl_app: **Передает данные о заказе:**\n*Категория машины \n*Статус машины\n*Номер машины\n*Имя водителя\n*Номер телефона водителя\n*Время подачи машины
orch-->dr_app: **Передает данные о заказе:**\n*Адрес подачи машины\n*Адрес назначения
deactivate orch
dr_app->dr: **Передает данные о заказе:**\n*Адрес подачи машины\n*Адрес назначения
cl_app->cl: **Передает данные о заказе:**\n*Категория машины \n*Статус машины\n*Номер машины\n*Имя водителя\n*Номер телефона водителя\n*Время подачи машины
alt
cl->cl_app: Отменяет заказ
cl_app->orch: Отменяет заказ
orch->dr_app: Отменяет заказ
dr_app->dr: Уведомляет об отмене заказа
orch-->cl_app: Подтверждает отмену заказа
end

orch->db: Сохранение данных о клиенте
orch->db: Сохранение данных о машине
orch->db: Сохранение данных о поездке
@enduml